name: TRIPSY
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.14.0
  firebase_auth: ^5.6.0
  cloud_firestore: ^5.6.9
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  geolocator: ^11.0.0
  google_maps_flutter: ^2.6.0
  cupertino_icons: ^1.0.8
  google_sign_in: ^6.1.5
  google_fonts: ^5.0.0
  animated_text_kit: ^4.2.2
  intl_phone_field: ^3.2.0
  provider: ^6.0.5
  firebase_messaging: ^15.2.10
  flutter_local_notifications: ^19.4.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.11.0
  build_runner: ^2.4.13
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    #- packages/intl_phone_field/assets/flags/
flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/loogo1.jpg"